### ISSUE TITLE
how do i actually run this (most likely skill issue on my side)

### ISSUE THREAD

**Issue by JanCantCode** [19MisterX98/TextureRotations#2]
i have inserted all my data and im now trying to actually run the programm.
what i have tried:
running the Main.java in the intellij Idea; doesn't work because i cant click the "run" in the first place
building it using gradle and then running it with java -jar; doesnt work, i get "no main manifest attribute found" which im pretty sure means it cant find the Main.java. 
running the Main.java file using the java  command from the console; doesnt work as it now fails to access imports from the project
`Main.java:1:` error: package texture does not exist
import texture.TextureProvider;
              ^
Main.java:2: error: package texture does not exist
import texture.VanillaTextures;
              ^
Main.java:3: error: package texture does not exist
import texture.SodiumTextures;
              ^
Main.java:4: error: package texture does not exist
import texture.Sodium19Textures;
              ^
Main.java:12: error: cannot find symbol
    public static final TextureProvider mode = new VanillaTextures();
                        ^
  symbol:   class TextureProvider
  location: class Main
Main.java:12: error: cannot find symbol
    public static final TextureProvider mode = new VanillaTextures();
                                                   ^
  symbol:   class VanillaTextures
  location: class Main
Main.java:24: error: cannot find symbol
            TextureFinder a = new TextureFinder(start,start+perX, mode);
            ^
  symbol:   class TextureFinder
  location: class Main
Main.java:24: error: cannot find symbol
            TextureFinder a = new TextureFinder(start,start+perX, mode);
                                  ^
  symbol:   class TextureFinder
  location: class Main
8 errors
error: compilation failed ``

**Comment by 19MisterX98** [comment]
Usually in Intellij you can click a green play button next to the main method.

**Comment by JanCantCode** [comment]
yeah, the button is grey instead of green, and when hovering over it, it says "The file in the editor is not runnable"

**Comment by JanCantCode** [comment]
if that is relevant, my Main.java looks like this: `import texture.TextureProvider;
import texture.VanillaTextures;
import texture.SodiumTextures;
import texture.Sodium19Textures;

public class Main {

    public static final int xMin = -30000, xMax = 30000;
    public static final int zMin = -30000, zMax = 30000;
    public static final int yMin = 10    , yMax = 80;
    public static final int threads = 1;
    public static final TextureProvider mode = new VanillaTextures();
    //                                         new SodiumTextures();
    //                                         new Sodium19Textures();

    //goto TextureFinder class to configure rotations

    public static void main(String[] args) {

        int xtotal = xMax - xMin;
        int perX = xtotal/threads;

        for (int start = xMin; start < xMax; start+= perX+1) {
            TextureFinder a = new TextureFinder(start,start+perX, mode);
            a.start();
        }

    }


}
`

**Comment by JanCantCode** [comment]
i got the files using git clone if thats somehow relevant

**Comment by JanCantCode** [comment]
update: i have managed to run it using java -cp, its running!
